package blargh.rpg;

import static blargh.rpg.Characteristics.AG;
import static blargh.rpg.Characteristics.BS;
import static blargh.rpg.Characteristics.DEX;
import static blargh.rpg.Characteristics.FEL;
import static blargh.rpg.Characteristics.I;
import static blargh.rpg.Characteristics.INT;
import static blargh.rpg.Characteristics.S;
import static blargh.rpg.Characteristics.T;
import static blargh.rpg.Characteristics.WP;
import static blargh.rpg.Characteristics.WS;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public enum Skills {
	ART_WRITING(DEX), ART_CALLIGRAPHY(DEX), ATHLETICS(AG), BRIBERY(FEL), CHARM(FEL), CHARM_ANIMAL(WP), 
	CLIMB(S), COOL(WP), CONSUME_ALCOHOL(T), DODGE(AG), DRIVE(AG), 
	ENDURANCE(T), ENTERTAIN_SPEECHES(FEL), ENTERTAIN_STORYTELLER(FEL), GAMBLE(INT), GOSSIP(FEL), HAGGLE(FEL), 
	INTIMIDATE(S), INTUITION(I), LEADERSHIP(FEL), MELEE_BASIC(WS), MELEE_ANY(WS), NAVIGATION(I), 
	OUTDOOR_SURVIVAL(INT), PERCEPTION(I), RIDE_HORSE(AG), ROW(S), STEALTH(AG),
	ANIMAL_CARE(INT), ANIMAL_TRAINING(INT), CHANNELING(WP), EVALUATE(INT), 
	HEAL(INT), LANGUAGE_CLASSICAL(INT), LANGUAGE_GUILDER(INT), LANGUAGE_KHAZALID(INT), LANGUAGE_ANY(INT), LORE_EMPIRE(INT), LORE_CHEMISTRY(INT), 
	LORE_MEDICINE(INT), LORE_PLANTS(INT), LORE_SCIENCE(INT), LORE_ENGINEER(INT), LORE_LAW(INT), LORE_THEOLOGY(INT), LORE_ANY(INT), LORE_LOCAL(INT), LORE_POLITICS(INT), 
	PERFORM(AG), PICK_LOCK(DEX), 
	PLAY(DEX), PRAY(FEL), RANGED_BLACKPOWDER(BS), RANGED_CROSSBOW(BS), RANGED_ENGINEERING(BS), RESEARCH(INT), SAIL(AG), 
	SECRET_SIGNS_GUILDER(INT), SET_TRAP(DEX), SLEIGHT_OF_HAND(DEX), SWIM(S), 
	TRACK(I), TRADE_APOTHECARY(DEX), TRADE_ENGINEER(DEX), TRADE_POISONER(DEX), TRADE_BREWER(DEX), TRADE_HERBALIST(DEX), TRADE_VINTNER(DEX);

	private Characteristics characteristic;
	private Skills() {}
	private Skills(Characteristics characteristic) {
		this.characteristic = characteristic;
	}

	public Characteristics characteristics() {
		return characteristic;
	}

	public static Set<Skills> basicSkills(){
		return new HashSet<>(Arrays.asList(ART_WRITING, ART_CALLIGRAPHY, ATHLETICS, BRIBERY, CHARM, CHARM_ANIMAL, CLIMB, COOL,
				CONSUME_ALCOHOL, DODGE, DRIVE, ENDURANCE, ENTERTAIN_SPEECHES, ENTERTAIN_STORYTELLER, GAMBLE,
				GOSSIP, HAGGLE, INTIMIDATE, INTUITION, LEADERSHIP, 
				MELEE_BASIC, MELEE_ANY,
				NAVIGATION, OUTDOOR_SURVIVAL, PERCEPTION, 
				RIDE_HORSE, 
				ROW, STEALTH));
	}
	
	public static Set<Skills> advancedSkills(){
		return new HashSet<>(Arrays.asList(ANIMAL_CARE, ANIMAL_TRAINING, CHANNELING, EVALUATE, HEAL, 
				LANGUAGE_CLASSICAL, LANGUAGE_GUILDER, LANGUAGE_KHAZALID, LANGUAGE_ANY, 
				LORE_EMPIRE, LORE_CHEMISTRY, LORE_ENGINEER, LORE_MEDICINE, LORE_PLANTS, LORE_SCIENCE, LORE_LAW, LORE_THEOLOGY, LORE_ANY, LORE_LOCAL, LORE_POLITICS, 
				PERFORM, PICK_LOCK, 
				PLAY, 
				PRAY, 
				RANGED_CROSSBOW, RANGED_BLACKPOWDER, RANGED_ENGINEERING, 
				RESEARCH, SAIL, 
				SECRET_SIGNS_GUILDER, 
				SET_TRAP, SLEIGHT_OF_HAND, SWIM, TRACK, 
				TRADE_APOTHECARY, TRADE_ENGINEER, TRADE_POISONER, TRADE_BREWER, TRADE_HERBALIST, TRADE_VINTNER));
	}
}
